apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: realfullstack-prod
nameSuffix: -prod
commonLabels:
  app-env: prod
configMapGenerator:
- behavior: merge
  envs:
  - files/config.env
  name: backend
patches:
- path: patches/sealed-secret.yaml
  target:
    group: bitnami.com
    kind: SealedSecret
    name: backend
    version: v1alpha1
images:
- name: backend_main
  newName: ghcr.io/realfullstack/backend/main_dev
  newTag: sha-27cc5de
- name: backend_nginx
  newName: ghcr.io/realfullstack/backend/nginx
  newTag: sha-27cc5de
resources:
- ../../base
