---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
spec:
  destination:
    namespace: realfullstack-prod
    server: "https://kubernetes.default.svc"
  project: realfullstack
  source:
    path: kustomize/overlays/prod
    repoURL: "https://github.com/realfullstack/backend-infra.git"
    targetRevision: HEAD
  # syncPolicy:
  #   automated: {}
