apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend
configurations:
    - conf/namereference.yaml
    - conf/commonlabels.yaml
commonLabels:
  app: backend
  app-project: courses
resources:
  # wave 0
  - configmap.yaml
  - secret.yaml
  # wave 1
  - sealed-secret.yaml
  - storage.yaml
  # wave 2
  - job.yaml
  # wave 3
  - deployment.yaml
  # wave 4
  - ingress.yaml
  - service.yaml